import type { Metadata } from 'next'

import './globals.css'
import { chewie, inter } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'NewsFeed — powered by NewsCatcher API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${chewie.variable} font-body`}>
        {/* <header className="bg-primary p-4 text-white">
          <div className="container flex justify-between">
            <h1 className="text-3xl font-bold">NewsFeed</h1>
          </div>
        </header> */}
        {/* <div className="container mx-auto flex justify-between"> */}
        {children}
      </body>
    </html>
  )
}
