import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NewsFeed',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-primary p-4 text-white">
          <div className="container mx-auto flex justify-between">
            <h1 className="text-3xl font-bold">NewsFeed</h1>
          </div>
        </header>
        <div className="container mx-auto flex justify-between">
          {children}
          <aside className="hidden w-80  p-4 lg:block">side content</aside>
        </div>
      </body>
    </html>
  )
}
